### ISSUE TITLE
Making Rails and Backbone Friends

### ISSUE THREAD

**Issue by emilylordahl** [emilylordahl/spirit_guide#6]
## CONTEXT

@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284
##### WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story "As a user, I want to save my search results to a profile so that I can  remember places that I've been to or want to visit."

I am working on the `relationships` branch of my repo.
##### WHAT YOU ARE TRYING TO DO:

I am trying to get the rendered search to save to a user's profile when the save button is clicked.
##### DETAILED DESCRIPTION OF THE BUG/ERROR:

The collection of search results is rendered with Backbone. I've set up tables with many to many relationships and can successfully create and remove relationships from the console, but I realized that is because I have a test market and business already in my database. That said, I'm not sure how to save a backbone model and then create the relationship on click with rails.

My controller is not very skinny, which is making me feel like I'm going about this the wrong way.

``` rb
class UsersController < ApplicationController

    def index
        render json: User.all
    end

    def show
        @user = User.find(params[:id])

        respond_to do |format|
            format.html {}
            format.json { render json: @user }
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            respond_to do |format|
                format.html { redirect_to users_path }
                format.json { render json: @user }
            end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: { error: 'New user not created', status: 400 } }
      end
    end
  end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])

        @user.update(user_params)

        respond_to do |format|
            format.html { redirect_to user_path(@user.id) }
            format.json { render json: @user }
        end
    end

    def destory
        @user = User.find(params[:id])

        @user.destroy

        respond_to do |format|
            format.html { redirect_to new_user_path }
            format.json { render json: @user }
        end
    end

    # def add_market
    #   user = User.find(params[:id])
    # end

    # def remove_market
    #   user = User.find(params[:id])
    # end

    def add_business
        user = User.find(params[:id])
        business = Business.find(params[:id])

        user.add_business(business)

        respond_to do |format|
            format.html { redirect_to user_path(user) }
            format.json { render json: @user }
        end
    end

    def remove_business
        user = User.find(params[:id])
        business = Business.find(params[:id])

        user.remove_business(business)

        respond_to do |format|
            format.html { redirect_to user_path(user) }
            format.json { render json: @user }
    end

    private
    def user_params
        params.require(:user).permit(:first_name,:last_name,:email,:password,:password_confirmation)
    end

end
```

``` js
App.Models.Business = Backbone.Model.extend({
    urlRoot: '/users/:id/add_user'
});
```
## WHAT I'VE TRIED

I've been using Tunr's playlist as a guide for creating many to many relationships and can make this work in the console, but I'm not sure the best way to save a model to my DB and then add the relationship.  Can I do that by setting a URL in my model? That's what makes sense to me, but I'm not sure if I'm using the right route to achieve this. Or should I just be making an AJAX call?

I've been reading some docs about trying to figure out how to save from backbone to rails and it seems that setting a URL in the model is the best way, but I am not sure what route that url should hit.
## QUESTION

Is there some sort of rails magic to save a backbone model? Now that I'm at this point where my collection has rendered, I'm not sure how to simultaneously save a model and create the relationship to the user.

:heart:
Emily

**Comment by WilliamfShaw** [comment]
@emilylordahl no rails magic, just make a call to your post route from backbone. Very simlar to how you would an express route. So you can use ajax or backbone url properties

**Comment by harimohanraj89** [comment]
@emilylordahl What is the status of this issue?

**Comment by emilylordahl** [comment]
Thank you @harimohanraj89 and @WilliamfShaw!!
